name: Windowsbuild
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
   windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
            
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - name: Install chocolatey before
        shell: cmd
        run: |
          powershell.exe -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))" 
          SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
          
      - name: Configure Cmake Visualstudio2022 Openssl
        run: |
          choco upgrade chocolatey
          choco install -y --skip-checksums --no-progress  cmake.install -y --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install -y --skip-checksums --no-progress  visualstudio2022-workload-nativedesktop
          choco install -y --skip-checksums --no-progress openssl --version=3.1.1
          # choco install -y --skip-checksums --no-progress mysql --version=8.0.31

      - name: Checkout Boost
        uses: actions/checkout@v3
        with:
          repository: 'boostorg/boost'
          submodules: true
          path: 'Boost'    

      - name: Configure Build Install Boost
        run: |
          cd Boost && mkdir __build__ && cd __build__
          cmake -DBUILD_SHARED_LIBS=ON ..
          cmake --build . -j 3
          cmake --build . -j 3 --target install
          
      - name: Configure Install MySQL
        shell: cmd
        run: |
         powershell.exe 
         winget install -e --id Oracle.MySQL -v 8.0.41 -l "C:\tools\mysql\current"

      - name: Checkout AzerothCore
        uses: actions/checkout@v3
        with:
          repository: 'liyunfan1223/azerothcore-wotlk'
          ref: 'Playerbot'

      - name: Checkout eluna Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-eluna'
          path: 'modules/mod-eluna'         
          
      - name: Checkout ah-bot Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-ah-bot'
          path: 'modules/mod-ah-bot'    

      - name: Checkout 1v1-arena Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-1v1-arena'
          path: 'modules/mod-1v1-arena'           

      - name: Checkout boss-announcer Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-boss-announcer'
          path: 'modules/mod-boss-announcer'  
          
      - name: Checkout npc-enchanter Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-npc-enchanter'
          path: 'modules/mod-npc-enchanter'           
          
      - name: Checkout Playerbot Module
        uses: actions/checkout@v3
        with:
          repository: 'liyunfan1223/mod-playerbots'
          path: 'modules/mod-playerbots'    
      - name: Build
        shell: bash
        run: |
          export CTOOLS_BUILD=all
          ./acore.sh compiler build    
