name: macos-build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# concurrency:
#   group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
#   cancel-in-progress: true

jobs:
  macos-build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - name: Checkout AzerothCore
        uses: actions/checkout@v4
        with:
          repository: 'liyunfan1223/azerothcore-wotlk'
          ref: 'Playerbot'
      - name: Checkout Playerbot Module
        uses: actions/checkout@v4
        with:
          repository: 'liyunfan1223/mod-playerbots'
          path: 'modules/mod-playerbots'
      - name: Checkout mod-1v1-arena
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-1v1-arena'
          path: 'modules/mod-1v1-arena'      
      - name: Checkout mod-ah-bot
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-ah-bot'
          path: 'modules/mod-ah-bot'
      - name: Checkout mod-low-level-rbg
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-low-level-rbg'
          path: 'modules/mod-low-level-rbg'
      - name: Checkout mod-npc-enchanter
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-npc-enchanter'
          path: 'modules/mod-npc-enchanter'
      - name: Checkout mod-npc-free-professions
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-npc-free-professions'
          path: 'modules/mod-npc-free-professionsr'
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/ccache
          key: ccache:${{ matrix.os }}:${{ github.ref }}:${{ github.sha }}
          restore-keys: |
            ccache:${{ matrix.os }}:${{ github.ref }}
            ccache:${{ matrix.os }}
      - name: Install latest bash
        run: brew install bash
      - name: Configure OS
        run: source ./acore.sh install-deps
      - name: Build
        run: source ./apps/ci/mac/ci-compile.sh
