name: windows-build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      BOOST_ROOT: C:\local\boost_1_82_0
    steps:
      - name: Checkout AzerothCore
        uses: actions/checkout@v3
        with:
          repository: 'liyunfan1223/azerothcore-wotlk'
          ref: 'Playerbot'
      - name: Checkout Playerbot Module
        uses: actions/checkout@v3
        with:
          repository: 'liyunfan1223/mod-playerbots'
          path: 'modules/mod-playerbots'
      - name: Checkout mod-1v1-arena
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-1v1-arena'
          path: 'modules/mod-1v1-arena'      
      - name: Checkout mod-ah-bot
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-ah-bot'
          path: 'modules/mod-ah-bot'
      - name: Checkout mod-low-level-rbg
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-low-level-rbg'
          path: 'modules/mod-low-level-rbg'
      - name: Checkout mod-npc-enchanter
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-npc-enchanter'
          path: 'modules/mod-npc-enchanter'
      - name: Checkout mod-npc-free-professions
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-npc-free-professions'
          path: 'modules/mod-npc-free-professionsr'
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.13
      - name: Configure OS
        shell: bash
        env:
          CONTINUOUS_INTEGRATION: true
        run: |
          ./acore.sh install-deps
      - name: Build
        shell: bash
        run: |
          export CTOOLS_BUILD=all
          ./acore.sh compiler build
      - name: Release
        uses: actions/create-release@v1
        with:
          files:  build/*
          draft: true
          fail_on_unmatched_files: true
