name: windows-build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      BOOST_ROOT: C:\local\boost_1_82_0
    steps:
      - name: Checkout AzerothCore
        uses: actions/checkout@v3
        with:
          repository: 'liyunfan1223/azerothcore-wotlk'
          ref: 'Playerbot'
          
      - name: Checkout eluna Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-eluna'
          path: 'modules/mod-eluna'         
          
      - name: Checkout ah-bot Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-ah-bot'
          path: 'modules/mod-ah-bot'    

      - name: Checkout 1v1-arena Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-1v1-arena'
          path: 'modules/mod-1v1-arena'           

      - name: Checkout boss-announcer Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-boss-announcer'
          path: 'modules/mod-boss-announcer'  
          
      - name: Checkout npc-enchanter Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-npc-enchanter'
          path: 'modules/mod-npc-enchanter'           
      - name: Checkout Playerbot Module
        uses: actions/checkout@v3
        with:
          repository: 'liyunfan1223/mod-playerbots'
          path: 'modules/mod-playerbots'
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.13
      - name: Configure OS
        shell: bash
        env:
          CONTINUOUS_INTEGRATION: true
        run: |
          ./acore.sh install-deps
      - name: Build
        shell: bash
        run: |
          export CTOOLS_BUILD=all
          ./acore.sh compiler build
      - name: Upload AzerothCore
        uses: actions/upload-artifact@v4
        with:
          name: AzerothCore-${{ env.BUILD_TIME }}
          path: ${{ github.workspace }}/build/*   
