name: windows-build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
   windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
            
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:        
      - name: Install chocolatey Visualstudio2022 Scoop  Cmake Openssl Mysql Boost
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          $env:PATH += ";$env:ALLUSERSPROFILE\chocolatey\bin"
          choco install -y --skip-checksums $INSTALL_ARGS  visualstudio2022-workload-nativedesktop
          irm get.scoop.sh | iex
          scoop update
          scoop install aria2
          scoop config aria2-warning-enabled false
          scoop install main/cmake
          scoop install main/openssl
          scoop install main/mysql-lts
          scoop install main/boost

      - name: Checkout AzerothCore
        uses: actions/checkout@v3
        with:
          repository: 'liyunfan1223/azerothcore-wotlk'
          ref: 'Playerbot'

      - name: Checkout eluna Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-eluna'
          path: 'modules/mod-eluna'         
          
      - name: Checkout ah-bot Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-ah-bot'
          path: 'modules/mod-ah-bot'    

      - name: Checkout 1v1-arena Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-1v1-arena'
          path: 'modules/mod-1v1-arena'           

      - name: Checkout boss-announcer Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-boss-announcer'
          path: 'modules/mod-boss-announcer'  
          
      - name: Checkout npc-enchanter Module
        uses: actions/checkout@v3
        with:
          repository: 'azerothcore/mod-npc-enchanter'
          path: 'modules/mod-npc-enchanter'           
          
      - name: Checkout Playerbot Module
        uses: actions/checkout@v3
        with:
          repository: 'liyunfan1223/mod-playerbots'
          path: 'modules/mod-playerbots'    
      - name: Build
        shell: bash
        run: |
          export CTOOLS_BUILD=all
          ./acore.sh compiler build    
